# 4. [BIGA] Answer 5.1 The List Data Type Work (and Using the SUM Function)
isuzu_market = float(145.95)
toyota_market = float( 215.123)
honda_market = float(195.65)
comparison = [isuzu_market, toyota_market, honda_market]
print(comparison)
print(sum(comparison))
print(type(comparison[0]))
print(type(comparison[1]))
print(type(comparison[2]))
print(type(comparison))